# PyTorch & Numpy

pytorch에서 활용할 수 있는 numpy의 기능들을 정리

In [1]:
import torch

---

## RNG

- CPU, GPU 모두 기본적으로 `torch.manual_seed()`로 제어 가능함.

In [2]:
torch.manual_seed(7)
print(torch.randn(10))

tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])


- When running on the CuDNN backend, two further options must be set:

In [3]:
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

- pytorch에서 다양한 확률 분포는 `torch.distributions` 모듈 참고!

## Vectorization

In [17]:
L = torch.tensor([[1., 0.], [1.5, 1.]])
U = torch.tensor([[4., 3.], [0., -1.5]])
print(f'Lower triangular matrix \n {L}')
print()
print(f'Upper triangular matrix \n {U}')

Lower triangular matrix 
 tensor([[1.0000, 0.0000],
        [1.5000, 1.0000]])

Upper triangular matrix 
 tensor([[ 4.0000,  3.0000],
        [ 0.0000, -1.5000]])


- tensor and scalar (element-wise)

In [18]:
L + 1

tensor([[2.0000, 1.0000],
        [2.5000, 2.0000]])

In [19]:
L - 1

tensor([[ 0.0000, -1.0000],
        [ 0.5000,  0.0000]])

In [20]:
L * 2

tensor([[2., 0.],
        [3., 2.]])

In [21]:
L / 2

tensor([[0.5000, 0.0000],
        [0.7500, 0.5000]])

In [22]:
L // 2 # floor division

tensor([[0., 0.],
        [0., 0.]])

In [24]:
U % 2 

tensor([[0.0000, 1.0000],
        [0.0000, 0.5000]])

In [25]:
U ** 2

tensor([[16.0000,  9.0000],
        [ 0.0000,  2.2500]])

In [26]:
2 ** U 

tensor([[16.0000,  8.0000],
        [ 1.0000,  0.3536]])

- tensor and tensor (element-wise)

In [27]:
L + U

tensor([[ 5.0000,  3.0000],
        [ 1.5000, -0.5000]])

In [28]:
L - U

tensor([[-3.0000, -3.0000],
        [ 1.5000,  2.5000]])

In [29]:
L * U

tensor([[ 4.0000,  0.0000],
        [ 0.0000, -1.5000]])

In [30]:
U / L

tensor([[ 4.0000,     inf],
        [ 0.0000, -1.5000]])

In [31]:
U // L

tensor([[ 4., inf],
        [ 0., -1.]])

In [33]:
L % U

tensor([[ 1.0000,  0.0000],
        [    nan, -0.5000]])

In [34]:
L ** U

tensor([[1., 0.],
        [1., 1.]])

- tensor and tensor compare (element-wise)

In [36]:
L == U

tensor([[False, False],
        [False, False]])

In [39]:
L <= U

tensor([[ True,  True],
        [False, False]])

In [38]:
L > U

tensor([[False, False],
        [ True,  True]])

- tensor and tensor assignment (element-wise)

In [41]:
I = torch.tensor([[1., 0.], [0., 1.]])

In [46]:
L += I

In [47]:
L

tensor([[2.0000, 0.0000],
        [1.5000, 2.0000]])

## Broadcasting

- 양 쪽으로 브로드캐스팅 될 경우 뒤부터 채우고 앞으로 브로드 캐스팅

In [84]:
torch.ones((2,2,4,3), dtype = torch.float32) + torch.arange(2, dtype = torch.float32).reshape(2,1,1)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]])

## Manipuate the shape

In [110]:
A = torch.arange(12, dtype = torch.float32).reshape(4, 3)

#### flatten

- flatten(or ravel) the tensor $\longrightarrow$ `.view(-1)`
    - new $\longrightarrow$ `.clone().view(-1)`

In [111]:
A.view(-1)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

#### tile

- 행렬에 대한 행렬

In [112]:
A.repeat(2,2)

tensor([[ 0.,  1.,  2.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  6.,  7.,  8.],
        [ 9., 10., 11.,  9., 10., 11.],
        [ 0.,  1.,  2.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  6.,  7.,  8.],
        [ 9., 10., 11.,  9., 10., 11.]])

#### squeeze

- (1, 3, 4) $\longrightarrow$ (3, 4)

In [116]:
A.view(1, 4, 3).squeeze().shape

torch.Size([4, 3])

#### unsqueeze

- shape의 원하는 dim에 axis 추가

In [117]:
A.unsqueeze(1).shape

torch.Size([4, 1, 3])

#### concatenate

In [134]:
x = torch.randn(2, 3)

In [135]:
torch.cat((x,x,x,x), dim = 0).shape

torch.Size([8, 3])

In [136]:
torch.cat((x,x,x,x), dim = 1).shape

torch.Size([2, 12])

#### stack

- broadcasting적으로 생각해

In [138]:
torch.stack((x,x,x,x), dim = 2).shape

torch.Size([2, 3, 4])

## Indexing

In [203]:
A = torch.arange(12).view(3,4)

- basic

In [172]:
A[0::2]

tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])

In [175]:
A[0::2][:,2:]

tensor([[ 2,  3],
        [10, 11]])

- boolean indexing

In [176]:
A = torch.randn(12).view(3,4)

In [194]:
A[A > 0]

tensor([1.2799, 1.8150, 1.6148, 1.9302])

In [198]:
new_A = A[(A >= 1) | (A <= -1)]

In [212]:
# 원래 tensor와 indexed tensor의 view가 동일하다.
id(A.storage()) == id(new_A.storage())

True

- Fancy indexing

In [231]:
A = torch.arange(12).view(3,4)

In [232]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [233]:
r = torch.tensor([1,2])

In [234]:
A[r]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [235]:
A[-r]

tensor([[ 8,  9, 10, 11],
        [ 4,  5,  6,  7]])

In [236]:
r_ix = torch.tensor([0,2])
c_ix = torch.tensor([1,3])

In [237]:
A[r_ix][:,-c_ix]

tensor([[ 3,  1],
        [11,  9]])

In [241]:
id(A.storage()) == id(A[r_ix][:,c_ix].storage())

True